AWS_ACCESS_KEY_ID: '1A2QWQJA4ZDXETJTJG02'
AWS_SECRET_ACCESS_KEY: '2apG8LB/Is7Dk4kgqEFPDMztV0rnY3TSNGTpblJ1'
asset_host_name: "assets%d.opencongress.org"     
# dry_run: false # Set to true if you want to test the asset_host uploading without doing anything on Amazon S3
