AWS_ACCESS_KEY_ID: "xxx"
AWS_SECRET_ACCESS_KEY: "xxx"
asset_host_name: "assets%d.opencongress.org"     
# dry_run: false # Set to true if you want to test the asset_host uploading without doing anything on Amazon S3
